SELECT
    $1:record_unique_identifier::NUMBER(38, 0) AS record_unique_identifier,
    $1:position_context_key::TEXT AS position_context_key,
    $1:position_cgl_booking_le_lkpid::TEXT AS position_cgl_booking_le_lkpid,
    $1:position_cgl_cntrprty_le_lkpid::TEXT AS position_cgl_cntrprty_le_lkpid,
    $1:asset_lri_asset_key::NUMBER(38, 0) AS asset_lri_asset_key,
    $1:stress_category_id_long_desc::TEXT AS stress_category_id_long_desc,
    $1:position_lri_native_currency_lkpid::TEXT AS position_lri_native_currency_lkpid,
    $1:cob_date::DATE AS cob_date,
    $1:position_cgl_booking_bu_lkpid::TEXT AS position_cgl_booking_bu_lkpid,
    $1:lri_lob_map_booking_lri_lob_desc_id::TEXT AS lri_lob_map_booking_lri_lob_desc_id,
    $1:lri_lob_map_booking_lri_lob_desc::TEXT AS lri_lob_map_booking_lri_lob_desc,
    $1:sls_category_id::TEXT AS sls_category_id,
    $1:stress_category_id::TEXT AS stress_category_id,
    $1:position_hqla_level::TEXT AS position_hqla_level,
    $1:run_type::TEXT AS run_type,
    $1:flow_result_flow_measure_name::TEXT AS flow_result_flow_measure_name,
    $1:position_sls_line_no::TEXT AS position_sls_line_no,
    $1:lri_asset_key_lic::NUMBER(38, 0) AS lri_asset_key_lic,
    $1:asset_cusip::TEXT AS asset_cusip,
    $1:asset_description::TEXT AS asset_description,
    $1:asset_gim_issr_entity_id::TEXT AS asset_gim_issr_entity_id,
    $1:asset_isin::TEXT AS asset_isin,
    $1:asset_maturity_dt::DATE AS asset_maturity_dt,
    $1:asset_name::TEXT AS asset_name,
    $1:report_line_rpt_signage::NUMBER(38, 0) AS report_line_rpt_signage,
    $1:sls_sls_asset_class::TEXT AS sls_sls_asset_class,
    $1:sls_sls_desc::TEXT AS sls_sls_desc,
    $1:sls_sls_lvl_1_ln_desc::TEXT AS sls_sls_lvl_1_ln_desc,
    $1:sls_sls_lvl_1_ln_no::TEXT AS sls_sls_lvl_1_ln_no,
    $1:sls_sls_lvl_2_ln_desc::TEXT AS sls_sls_lvl_2_ln_desc,
    $1:sls_sls_lvl_2_ln_no::TEXT AS sls_sls_lvl_2_ln_no,
    $1:sls_sls_lvl_3_ln_desc::TEXT AS sls_sls_lvl_3_ln_desc,
    $1:sls_sls_lvl_3_ln_no::TEXT AS sls_sls_lvl_3_ln_no,
    $1:sls_sls_lvl_4_ln_desc::TEXT AS sls_sls_lvl_4_ln_desc,
    $1:sls_sls_lvl_4_ln_no::TEXT AS sls_sls_lvl_4_ln_no,
    $1:sls_sls_sort::TEXT AS sls_sls_sort,
    $1:sls_cdg1_map::TEXT AS sls_cdg1_map,
    $1:sls_is_leaf::TEXT AS sls_is_leaf,
    $1:intercompany_is_inter_lob::TEXT AS intercompany_is_inter_lob,
    $1:booking_bu_profit_cc_cd::TEXT AS booking_bu_profit_cc_cd,
    $1:lri_lob_map_cntrprty_lri_lob_desc_id::TEXT AS lri_lob_map_cntrprty_lri_lob_desc_id,
    $1:position_sls_product_id::TEXT AS position_sls_product_id,
    $1:lri_lob_map_cntrprty_lri_lob_desc::TEXT AS lri_lob_map_cntrprty_lri_lob_desc,
    $1:position_adjustment_type_cd::TEXT AS position_adjustment_type_cd,
    $1:product_category_master_category_long_desc::TEXT AS product_category_master_category_long_desc,
    $1:flow_result_flow_asset_class_cd::TEXT AS flow_result_flow_asset_class_cd,
    $1:intercompany_intercompany_ind::TEXT AS intercompany_intercompany_ind,
    $1:asset_issuer_type::TEXT AS asset_issuer_type,
    $1:flow_result_flow_direction_cd::TEXT AS flow_result_flow_direction_cd,
    $1:flow_result_flow_reason_cd::TEXT AS flow_result_flow_reason_cd,
    $1:report_rpt_map_rule_id::NUMBER(38, 0) AS report_rpt_map_rule_id
FROM
@PROD_107923_DB.LRI_BASE.CADSS3_LRSS_PROD_REFINED/refined/com.jpmorgan.ct.stress/dbox_acc_v0_5/__qomo__user_tx_id=601240718000322798/
    (FILE_FORMAT => 'LRI_BASE.FILE_FORMAT_PARQUET') t
where
    INTERCOMPANY_RPTG_LE = '3586'
LIMIT 10000;
